# The structure for reference purposes
> str(mysis.len)
'data.frame':   89 obs. of  30 variables:
 $ include.L : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ include.LW: logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ purpose   : Factor w/ 3 levels "L","L,LW","LW": 2 2 2 2 2 2 2 2 2 2 ...
 $ use.lw    : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ use.l     : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ tech      : Factor w/ 2 levels "EJ","Kate": 1 1 1 1 1 1 1 1 1 1 ...
 $ batch     : Factor w/ 3 levels "1","2","NA": 1 1 1 1 1 1 1 1 1 1 ...
 $ id        : num  507 508 509 510 511 512 513 517 519 522 ...
 $ tin.id    : Factor w/ 191 levels "501","502","503",..: 7 174 8 174 174 174 174 12 14 17 ...
 $ photo.id  : Factor w/ 190 levels "001-3","002-3",..: 183 184 184 184 185 185 185 187 187 188 ...
 $ date      : chr  "2006-10-05" "2006-10-05" "2006-10-05" "2006-10-05" ...
 $ time      : chr  "21:17:00" "21:17:00" "21:17:00" "21:17:00" ...
 $ station   : Factor w/ 6 levels "171","Grid 1409",..: 5 5 5 5 5 5 5 5 5 5 ...
 $ tx        : Factor w/ 2 levels "8BF","8SBF": 1 1 1 1 1 1 1 1 1 1 ...
 $ stage     : Factor w/ 3 levels "Fem","Juv","Male": 1 2 2 2 2 2 2 1 1 1 ...
 $ len.fr.bin: num  9 7 9 7 7 7 7 15 15 9 ...
 $ len.fr    : num  10.2 7.6 9.4 7.5 7.6 7.7 7.9 15.3 16 10.5 ...
 $ len.p2w   : num  9.4 6.8 8.4 7.3 7.3 7.5 7.7 15.1 15.8 9.8 ...
 $ len.p2m   : num  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...
 $ raw.wt    : num  1e-03 8e-04 9e-04 7e-04 9e-04 ...
 $ c.wt      : num  0.00177 0.00080 0.00167 0.00070 0.00090 ...
 $ len       : num  9.4 6.8 8.4 7.3 7.3 7.5 7.7 15.1 15.8 9.8 ...
 $ len.bin   : num  9 5 7 7 7 7 7 15 15 9 ...
 $ notes     : Factor w/ 29 levels "changed purpose to LW (from L,LW) b/c no fresh length was recorded",..: 14 3 14 3 3 3 3 14 14 14 ...
 $ group     : Factor w/ 6 levels "Fem:8BF","Fem:8SBF",..: 1 3 3 3 3 3 3 1 1 1 ...
 $ loss.p2w  : num  -0.8 -0.8 -1.0 -0.2 -0.3 ...
 $ loss.p2m  : num  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...
 $ ploss.p2w : num  -0.0784 -0.1053 -0.1064 -0.0267 -0.0395 ...
 $ ploss.p2m : num  NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN ...

# load needed libraries
library(NCStats)
library(xlsReadWrite)                                        # load package to make reading and writing from Excel easier

# Data entry, cleaning, and variable creation
mysis <- read.xls("Mysis_Data_Master.xls",sheet="Mysis",     # must change directory to where data file is
colClasses=c("logical","logical","factor","logical",         # this argument needed so that len.p2w is loaded as a numeric and not a factor (b/c of NA)
"logical","factor","factor","numeric","factor","factor","isodate","isotime","factor","factor","factor","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","factor")) 
mysisL <- mysis[mysis$include.L,]                            # excludes values not to be included
mysis.len <- mysisL[mysisL$use.l,]                           # just a data frame for length analysis
mysis.len$tx <- factor(mysis.len$tx)                         # this is needed to remove the "Fresh" level which is not included in this analysis.
mysis.len$stage <- factor(mysis.len$stage)                   # this is needed to remove the "Gravid" level which is not included in this analysis.
mysis.len$group <- mysis.len$stage:mysis.len$tx              # creates a group variable that is a combination of the stage and treatment.
mysis.len$loss.p2w <- mysis.len$len.p2w-mysis.len$len.fr     # computes loss in length for 2 weeks preservation (negative means loss)
mysis.len$loss.p2m <- mysis.len$len.p2m-mysis.len$len.fr     # same but for 2 months preservation
mysis.len$ploss.p2w <- mysis.len$loss.p2w/mysis.len$len.fr   # computes proportional loss in length for 2 weeks perservation
mysis.len$ploss.p2m <- mysis.len$loss.p2m/mysis.len$len.fr   # same but for 2 months preservation
attach(mysis.len)

# Sample Summaries
ftable(xtabs(~tx+stage))                                     # get sample sizes -- not in ms (use no juvies below)
ftable(xtabs(~tx+stage+len.fr.bin))                          #  not in ms (use no juvies below)
tapply(len.fr,stage:tx,Summary,na.rm=T)                      # sample summaries of length --  not in ms (use no juvies below)
tapply(loss.p2w,stage:tx,Summary,na.rm=T)                    # sample summaries of loss in length --  not in ms (use no juvies below)

# initial model fits on absolute loss
lm1 <- lm(loss.p2w~len.fr*stage*tx)                          # not in ms -- decided to remove juveniles to match LW work
Anova(lm1)                                                   # no slope differences, intercepts differ by treatment
plot.fit(lm1,legend="topleft")

# Without juveniles #################################
detach(mysis.len)
mysis.len2 <- subset(mysis.len,stage!="Juv")                 # removes juveniles
mysis.len2$stage <- factor(mysis.len2$stage)                 # refactors stage so that juvenile label is removed
mysis.len2$group <- factor(mysis.len2$group)                 # same with group factor
attach(mysis.len2)

# Sample Summaries
ftable(xtabs(~tx+stage))                                     # get sample sizes -- in ms
tapply(len.fr,stage:tx,Summary,na.rm=T)                      # sample summaries of length --  in ms
tapply(loss.p2w,stage:tx,Summary,na.rm=T)                    # sample summaries of loss in length --  in ms

# model fits on absolute loss
lm2 <- lm(loss.p2w~len.fr*stage*tx)
Anova(lm2)                                                   # in ms
plot.fit(lm2,legend="topleft")


t.test(loss.p2w)                                             # in ms
p <- prop.table(table(round(loss.p2w,1)))
sum(p[1:6])                                                  # lost length -- in ms
sum(p[8:9])                                                  # gained length -- in ms

detach(mysis.len2)
